name: Unzip and Push File

permissions:
  contents: write

on:
  push:
    paths:
      - '**/*.zip'

jobs:
  unzip_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find the uploaded ZIP file
        shell: bash
        run: |
          FILE=$(find . -type f -name "*.zip" | head -n 1)
          echo "ZIP_FILE=$FILE" >> $GITHUB_ENV

      - name: Unzip the file with encoding fix
        if: env.ZIP_FILE != ''
        run: |
          unzip -O utf-8 $ZIP_FILE -d extracted_files/ || \
          (unzip $ZIP_FILE -d extracted_files/ && \
           find extracted_files/ -depth -execdir rename 's/[^A-Za-z0-9._-]/_/g' {} \;) 

      - name: Delete the original ZIP file
        run: |
          if [ -n "$ZIP_FILE" ]; then
            rm "$ZIP_FILE"
          fi

      - name: Rename HTML file to index.html
        run: |
          HTML_FILE=$(find extracted_files/ -type f -name "*.html" | head -n 1)
          if [ -n "$HTML_FILE" ]; then
            mv "$HTML_FILE" extracted_files/index.html
          fi

      - name: Add favicon links to index.html
        run: |
          if [ -f "extracted_files/index.html" ]; then
            sed -i 's|</head>|<link rel="apple-touch-icon" sizes="180x180" href="./favicon/apple-touch-icon.png">\n<link rel="icon" type="image/png" sizes="32x32" href="./favicon/favicon-32x32.png">\n<link rel="icon" type="image/png" sizes="16x16" href="./favicon/favicon-16x16.png">\n<link rel="manifest" href="./favicon/site.webmanifest">\n<link rel="mask-icon" href="./favicon/safari-pinned-tab.svg" color="#5bbad5">\n<meta name="msapplication-TileColor" content="#da532c">\n<meta name="theme-color" content="#ffffff">\n</head>|' extracted_files/index.html
          fi

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit unzipped files
        run: |
          if [ -d "extracted_files" ]; then
            mv extracted_files/* ./
            rm -rf extracted_files
            git add .
            git commit -m "Unzipped and committed files from $ZIP_FILE"
          fi

      - name: Push changes
        run: git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
